version: '3'

services:
  file-decompressor:
    build: .
    container_name: file-auto-decompressor
    volumes:
      - /path/to/downloads:/downloads        # Change this to your downloads directory
      - /path/to/output:/download_files      # Change this to your output directory
      - ./logs:/logs                         # Local logs directory
    restart: always
