version: '3'

services:
  file-decompressor:
    build: .
    container_name: file-auto-decompressor
    volumes:
      - /path/to/downloads:/downloads        # Change this to your downloads directory
      - /path/to/output:/download_files      # Change this to your output directory
    environment:
      # Comma-separated list of default passwords to try for password-protected archives
      # Example: DEFAULT_PASSWORDS=password123,admin,123456
      - DEFAULT_PASSWORDS=${DEFAULT_PASSWORDS:-}
    restart: always
